#\!/bin/bash

echo "Instrucciones para instalación manual de HEC-HMS:"
echo "=================================================="
echo ""
echo "1. Descarga el archivo HEC-HMS manualmente desde Google Drive"
echo "2. Súbelo al servidor en el directorio /tmp/"
echo "3. Ejecuta estos comandos:"
echo ""
echo "   # Si el archivo es .tar.gz:"
echo "   sudo mkdir -p /opt/hms"
echo "   tar -xzf /tmp/tu_archivo_hms.tar.gz -C /tmp/"
echo "   sudo mv /tmp/HEC-HMS-*/* /opt/hms/ 2>/dev/null || sudo mv /tmp/* /opt/hms/"
echo "   sudo chmod -R 755 /opt/hms"
echo "   sudo chmod +x /opt/hms/hec-hms.sh"
echo ""
echo "   # Si el archivo es .zip:"
echo "   sudo mkdir -p /opt/hms"
echo "   unzip /tmp/tu_archivo_hms.zip -d /tmp/"
echo "   sudo mv /tmp/HEC-HMS-*/* /opt/hms/ 2>/dev/null || sudo mv /tmp/* /opt/hms/"
echo "   sudo chmod -R 755 /opt/hms"
echo "   sudo chmod +x /opt/hms/hec-hms.sh"
echo ""
echo "4. Después ejecuta de nuevo el script de setup y salta el paso 8"
