# Configuration file for HEC-HMS Historical Scripts (Linux/WSL version)

project:
  name: "LeonCreek HMS Historical"
  version: "1.0"

software_paths:
  hec_hms: /opt/hms
  jython: /opt/jython.jar
  vortex: /opt/hms/lib
  hec_dssvue: /opt/hms

data_paths:
  project_root: /mnt/d/Floodace Projects/HEC-HMS-BackEnd
  grb_downloads_subdir: grb_downloads
  shapefiles_subdir: gis_data/shapefiles
  hms_model_base_subdir: hms_models
  dss_source_subdir: dss_files/incoming
  dss_merged_subdir: hms_models/Historical/LeonCreek/Rainfall

system:
  temp_files_dir: /tmp/floodace_temp

# Grib download settings
grib_download:
  # URL pattern: use {YYYY}, {MM}, {DD} as placeholders
  base_url: "https://mtarchive.geol.iastate.edu/{YYYY}/{MM}/{DD}/mrms/ncep/MultiSensor_QPE_24H_Pass2/"
  # Regex pattern to match files to download
  file_pattern: "MultiSensor_QPE_24H_Pass2_00.00_.*\\.grib2\\.gz$"
  # Connection timeout in seconds
  timeout: 30
  # Max retry attempts
  max_retries: 3

models:
  leon_creek:
    dir: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/Historical/LeonCreek
    name: "Leon Creek Model"
    
    shapefile: 
      name: Bexar_County.shp
      path: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/gis_data/shapefiles/Bexar_County.shp
    
    dss_files:
      rainfall_historical: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/Historical/LeonCreek/Rainfall/RainfallHistorical.dss
      output_historical: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/Historical/LeonCreek/RainHistorical.dss
    
    control_files:
      historical: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/Historical/LeonCreek/RainHistorical.control

# DSS record paths
dss_records:
  precipitation_gridded: "//BEXAR_COUNTY/PRECIPITATION-INC-SPATIAL///GRIB_DATA/"
  # Junction flow paths for output extraction
  junction_flows:
    - "//J410/FLOW/PLAN/RUN:RUN 1/"
    - "//J420/FLOW/PLAN/RUN:RUN 1/"
    - "//J430/FLOW/PLAN/RUN:RUN 1/"

# Python environments
python_envs:
  hms: /home/${USER}/miniconda3/envs/hechmsfloodace/bin/python
  grib2cog: /home/${USER}/miniconda3/envs/grib2cog/bin/python