# Configuration for HEC-HMS Floodace Scripts (Windows Server Environment)

install_paths:
  # --- External Software Installation Paths ---
  # IMPORTANT: These paths MUST match the actual installation location on the server.
  # Using standard locations is recommended for consistency. Ensure the specified versions are installed.
  hec_hms: C:/Program Files/HEC/HEC-HMS/4.12   # Example Windows path for HEC-HMS 4.12
  #jython: C:/Program Files/HEC/HEC-DSSVue
  jython: C:/jython2.7.4                      # Example Windows path for Jython 2.7.4 (adjust if needed)
  #vortex: C:/Program Files/HEC/HEC-Vortex/vortex-0.11.25 # Example Windows path (adjust based on actual install)
  vortex: C:/Program Files/HEC/vortex-0.11.25 # Example Windows path (adjust based on actual install)
  hec_dssvue: "C:/Program Files/HEC/HEC-DSSVue"

data_paths:
  # --- Project Data Subdirectories ---
  # These paths are RELATIVE to the directory containing this config.yaml file.
  grb_downloads_subdir: D:/FloodaceDocuments/HMS\HMSGit/HEC-HMS-Floodace/grb_downloads
  shapefiles_subdir: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/gis_data/shapefiles
  hms_model_base_subdir: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models
  dss_source_subdir: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/dss_files/incoming
  dss_merged_subdir: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek/Rainfall

  # --- Standalone Paths ---
  # Directory for temporary files (can be absolute or relative)
  temp_files_dir: C:/Temp/floodace_temp

hms_projects:
  # Configuration specific to the Leon Creek project
  leon_creek:
    # Directory name (relative to data_paths.hms_model_base_subdir)
    directory_name: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek               # Ensure this matches the folder name on disk
    basin_file_name: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek/Leon_Watershed.basin       # Exact .basin filename
    output_dss_suffix: "_Batch_Name"        # Suffix for DSS files generated by testhec.py

merge_grb:
  # Shapefile name (relative to data_paths.shapefiles_subdir)
  clip_shapefile_name: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/gis_data/shapefiles/Bexar_County.shp       # The .shp filename
  variables: ["RadarOnly_QPE_01H_altitude_above_msl"] # Variables to extract
  variablesv2: ["RadarOnly_QPE_15M_altitude_above_msl"] # Variables to extract (Key Renamed)
  variablesv3: ["MultiSensor_QPE_01H_Pass1_altitude_above_msl"] # Variables to extract (Key Renamed)
  variablesv4: ["MultiSensor_QPE_01H_Pass2_altitude_above_msl"] # Variables to extract (Key Renamed)
  #variablesv3: ["Total_precipitation_surface_1_Hour_Accumulation"] # Variables to extract (Key Renamed)
  # Full path still recommended here, or construct it relative to project root + hms model path
  output_dss_path: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek/Rainfall/RainfallRealTime.dss # Updated path
  output_dss_path_pass2: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek/Rainfall/RainfallRealTimePass2.dss # Updated path
  output_dss_path_pass1_pass2: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek/Rainfall/RainfallRealTimePass1And2.dss # Updated path

merge_dss:
  # Filename for the merged DSS file (will be placed under data_paths.dss_merged_subdir)
  merged_filename: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/Rainfall.dss

jython:
  # Memory settings for Jython processes
  initial_heap: "256m"
  max_heap: "16384m"

merge_hrrr_forecast:
  # Configuration for merging HRRR forecast GRIB files
  clip_shapefile_name: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/gis_data/shapefiles/Bexar_County.shp       # Assuming the same clip shapefile
  variables: ["Total_precipitation_surface_Mixed_intervals_Accumulation"] # HRRR specific variable
  output_dss_path: D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek/Rainfall/HRR.dss # DSS file for HRRR data

grib_download:
  # NOAA NOMADS settings (for historical/other sources)
  base_url: "https://mtarchive.geol.iastate.edu/####/##/##/mrms/ncep/MultiSensor_QPE_01H_Pass2/"
  base_url_realtime: "https://mrms.ncep.noaa.gov/2D/MultiSensor_QPE_01H_Pass1/"
  # String pattern to identify relevant GRIB files (e.g., "01h" for 1-hour accumulation)
  file_pattern: ""

# grib_download:
#   # NOAA NOMADS settings (for historical/other sources)
#   base_url: "https://nomads.ncep.noaa.gov/pub/data/nccf/com/pcpanl/prod/"
#   # String pattern to identify relevant GRIB files (e.g., "01h" for 1-hour accumulation)
#   file_pattern: "01h"

  # MRMS Real-time settings (NEW)
  mrms_realtime:
    base_url: "https://mrms.ncep.noaa.gov/2D/RadarOnly_QPE_15M/"
    # Note: file_pattern is not needed here; script filters by date in filename

# --- NEW SECTION FOR DSS TIME SERIES EXTRACTION ---
dss_time_series_extraction:
  # Configuration for extracting time series data from a DSS file using the Jython script.

  # Path to the DSS file from which data will be extracted.
  # This can be an absolute path (e.g., "C:/path/to/your/data.dss")
  # or a path relative to the project root (e.g., "hms_models/LeonCreek/Rainfall/RainfallRealTime.dss").
  # Please verify this path and update it to point to your desired DSS file.
  dss_file_path: "D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek/RainrealTime.dss"
  dss_file_path_pass2: "D:/FloodaceDocuments/HMS/HMSGit/HEC-HMS-Floodace/hms_models/LeonCreek/RainrealTimePass2.dss"

  # The full DSS pathname for the specific time series record you want to extract.
  # Format: /A_PART/B_PART/C_PART/D_PART/E_PART/F_PART/
  # (Example from your provided image context)
    # --- Option 2: Store individual fixed parts (more flexible) ---
  pathname_part_a: ""  # Or your actual A part, e.g., "MYPROJECT"
  # B_PART will come from script input
  pathname_part_c: "FLOW"
  pathname_part_d: ""  # Or a specific date block if needed
  pathname_part_e: "1HOUR"
  pathname_part_f: "RUN:RainrealTime"

  # Optional: Start of the time window for data extraction.
  # Format should be "ddMMMyyyy HH:mm" (e.g., "12MAY2025 00:00").
  # Leave as an empty string ("") or null if you want to read from the beginning of the record.
  start_time_window: ""

  # Optional: End of the time window for data extraction.
  # Format should be "ddMMMyyyy HH:mm" (e.g., "15MAY2025 23:59").
  # Leave as an empty string ("") or null if you want to read to the end of the record.
  end_time_window: ""