# Configuration file for HEC-HMS Real-Time Scripts (Linux/WSL version)

project:
  name: "LeonCreek HMS Real-Time"
  version: "1.0"

software_paths:
  hec_hms: /opt/hms
  # Jython will be called as: java -jar /opt/jython.jar
  jython: /opt/jython.jar
  # Vortex might need to be installed separately or use HMS libraries
  vortex: /opt/hms/lib
  hec_dssvue: /opt/hms

data_paths:
  project_root: /mnt/d/Floodace Projects/HEC-HMS-BackEnd
  # Using forward slashes for all paths
  grb_downloads_subdir: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/grb_downloads
  shapefiles_subdir: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/gis_data/shapefiles
  hms_model_base_subdir: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models
  dss_source_subdir: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/dss_files/incoming
  dss_merged_subdir: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek/Rainfall

system:
  # Using /tmp for Linux temporary files
  temp_files_dir: /tmp/floodace_temp

models:
  leon_creek:
    # Base directory for the Leon Creek model
    dir: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek
    name: "Leon Creek Model"
    
    shapefile: 
      name: Bexar_County.shp
      path: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/gis_data/shapefiles/Bexar_County.shp
    
    dss_files:
      # Where merged real-time rainfall data will be written
      rainfall_realtime: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek/Rainfall/RainfallRealTime.dss
      # Output DSS file from HMS run
      output_realtime: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek/RainrealTime.dss
      # Historical rainfall data
      rainfall_historical: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/Historical/LeonCreek/Rainfall/RainfallHistorical.dss
      # HRRR forecast data
      hrrr_forecast: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek/Rainfall/HRR.dss
      # Pass 2 rainfall data
      rainfall_pass2: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek/Rainfall/RainfallRealTimePass2.dss
      # Combined Pass1 and Pass2
      rainfall_pass1_pass2: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek/Rainfall/RainfallRealTimePass1And2.dss
      # Combined real-time and forecast
      rainfall_realtime_forecast: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek/Rainfall/RainfallRealTimeAndForcast.dss
    
    # Control files
    control_files:
      realtime: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/RealTime/LeonCreek/RainRealTime.control
      historical: /mnt/d/Floodace Projects/HEC-HMS-BackEnd/hms_models/Historical/LeonCreek/RainHistorical.control

# DSS record paths
dss_records:
  precipitation_gridded: "//BEXAR_COUNTY/PRECIPITATION-INC-SPATIAL///GRIB_DATA/"
  precip_forecast: "//BEXAR_COUNTY/PRECIPITATION///GRIB_DATA/"
  # Junction flow paths for output extraction
  junction_flows:
    - "//J410/FLOW/PLAN/RUN:RUN 1/"
    - "//J420/FLOW/PLAN/RUN:RUN 1/"
    - "//J430/FLOW/PLAN/RUN:RUN 1/"

# Python environments (using conda)
python_envs:
  hms: /home/${USER}/miniconda3/envs/hechmsfloodace/bin/python
  grib2cog: /home/${USER}/miniconda3/envs/grib2cog/bin/python